Revert "Remove global seccomp list."
error: use of undeclared identifier 'set_global_seccomp_filter'

This reverts commit da46be2ad23052a51300a71237a99893922056e2.