Revert "Track library name change."
error: bionic/libm/Android.bp:6:1: "libm" depends on undefined module "libarm-optimized-routines-math"

This reverts commit ab9aa7f7ecef522bf4036c5d004334370cae20ca.