Revert "Use builtins for fma/fmax/fmin/nearbyint/rint/round/trunc on 32-bit ARM"
error: bionic/libm/Android.bp:287:20: unrecognized property "arch.arm.aarch32"

This reverts commit c6021225c3270809e53a0f1346fbfaa91c7c8cf0.

Change-Id: I66a2147a332fbbc321e77b2a375f495c7b1bc6ea