Revert "Speed up seccomp with priority list."
error: use of undeclared identifier 'set_global_seccomp_filter'

This reverts commit 2ccae5216655f0a79d2b2695674fa55708cb0b9d.